:- set_prolog_flag(occurs_check, error).        
:- set_prolog_stack(global, limit(8 000 000)). 
:- set_prolog_stack(local,  limit(2 000 000)). 
left(X, Y, [X | [Y | _]]).
left(X, Y, [_ | List]) :- left(X, Y, List).
neighbour(X, Y, List) :- left(X, Y, List); left(Y, X, List).
resolve :- Houses = [_, _, _, _, _],
  Houses = [house(norwegian, _, _, _, _), _, _, _, _],
  member(house(englishman, red, _, _, _), Houses),
  member(house(swedish, _, dog, _, _), Houses),
  member(house(danish, _, _, cha, _), Houses),
  left(house(_, green, _, _, _), house(_, white, _, _, _), Houses),
  member(house(_, green, _, coffee, _), Houses),
  member(house(_, _, bird, _, pallmall), Houses),
  member(house(_, yellow, _, _, dunhill), Houses),
  Houses = [_, _, house(_, _, _, milk, _), _, _],
  neighbour(house(_, _, _, _, blends), house(_, _, cat, _, _), Houses),
  neighbour(house(_, _, horse, _, _), house(_, _, _, _, dunhill), Houses),
  member(house(_, _, _, beer, bluemaster), Houses),
  member(house(german, _, _, _, prince), Houses),
  neighbour(house(norwegian, _, _, _, _), house(_, blue, _, _, _), Houses),
  neighbour(house(_, _, _, _, blends), house(_, _, _, water, _), Houses),
  Houses = [C1, C2, C3, C4, C5],
  C1 = house(C1_NATIONALITY, C1_COLOR, C1_PET, C1_DRINK, C1_SMOKE),
  C2 = house(C2_NATIONALITY, C2_COLOR, C2_PET, C2_DRINK, C2_SMOKE),
  C3 = house(C3_NATIONALITY, C3_COLOR, C3_PET, C3_DRINK, C3_SMOKE),
  C4 = house(C4_NATIONALITY, C4_COLOR, C4_PET, C4_DRINK, C4_SMOKE),
  C5 = house(C5_NATIONALITY, C5_COLOR, C5_PET, C5_DRINK, C5_SMOKE), nl,
  print('1ª House:'), nl,
  print('Color:'), print(C1_COLOR), nl,
  print('nationality:'), print(C1_NATIONALITY), nl,
  print('Beer:'), print(C1_DRINK), nl,
  print('Cigarette:'), print(C1_SMOKE), nl,
  print('Animal:'), print(C1_PET), nl, nl,
  print('2ª House:'), nl,
  print('Color:'), print(C2_COLOR), nl,
  print('nationality:'), print(C2_NATIONALITY), nl,
  print('Beer:'), print(C2_DRINK), nl,
  print('Cigarette:'), print(C2_SMOKE), nl,
  print('Animal:'), print(C2_PET), nl, nl,
  print('3ª House:'), nl,
  print('Color:'), print(C3_COLOR), nl,
  print('nationality:'), print(C3_NATIONALITY), nl,
  print('Beer:'), print(C3_DRINK), nl,
  print('Cigarette:'), print(C3_SMOKE), nl,
  print('Animal:'), print(C3_PET), nl, nl,
  print('4ª House:'), nl,
  print('Color:'), print(C4_COLOR), nl,
  print('nationality:'), print(C4_NATIONALITY), nl,
  print('Beer:'), print(C4_DRINK), nl,
  print('Cigarette:'), print(C4_SMOKE), nl,
  print('Animal:'), print(C4_PET), nl, nl,
  print('5ª House:'), nl,
  print('Color:'), print(C5_COLOR), nl,
  print('nationality:'), print(C5_NATIONALITY), nl,
  print('Beer:'), print(C5_DRINK), nl,
  print('Cigarette:'), print(C5_SMOKE), nl,
  print('Animal:\t'), print(C5_PET), nl, nl, nl.
